# Spring application name
spring.application.name=amsmanagament-system

# MySQL database connection
spring.datasource.url=jdbc:mysql://localhost:3306/agromanagment?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=pitamber???##
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true


# Twilio Credentials
twilio.accountSid=AC663093b5ee0e1675f83f51194156aba4
twilio.authToken=7fddae8bd2e4bd1eb9ef00c5ef8876a0
twilio.phoneNumber=+18564215651


